
[package]
authors = ["Ibrahim"]
edition = "2021"
name = "to_mp4"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.0.0"
napi-derive = "3.0.0"
openh264 = "0.8.1"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
